# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reference_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activated', models.BooleanField(default=False)),
                ('expiration', models.DateTimeField(default=django.utils.timezone.now)),
                ('emails', models.TextField(blank=True)),
            ],
        ),
    ]
