# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reference_stats', '0002_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
