# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-07 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_stats', '0003_activation_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='name',
        ),
    ]
