# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171205_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calendar_preference',
            field=models.CharField(choices=[('1', 'Spaces'), ('2', 'Calendar')], default='2', max_length=60),
        ),
    ]
