# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171205_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calendar_preference',
            field=models.CharField(choices=[('1', 'Spaces'), ('2', 'Calendar')], default='1', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='startup_page',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.IntranetURL'),
        ),
    ]
