# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171205_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calendar_preference',
            field=models.CharField(choices=[('spaces', 'Spaces'), ('calendar', 'Calendar')], default='spaces', max_length=60),
        ),
    ]
