# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarBranchMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LibCal_Branch_ID', models.PositiveIntegerField()),
                ('LibCal_Calendar_ID', models.PositiveIntegerField()),
                ('Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libcal_branches', to='accounts.Branch')),
            ],
        ),
    ]
