# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libcal', '0001_initial_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarbranchmapping',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='calendarbranchmapping',
            old_name='LibCal_Branch_ID',
            new_name='libcal_branch_id',
        ),
        migrations.RenameField(
            model_name='calendarbranchmapping',
            old_name='LibCal_Calendar_ID',
            new_name='libcal_calendar_id',
        ),
    ]
