# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libcal', '0003_setupteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupteam',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
