# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libcal', '0005_setupcomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupcomplete',
            old_name='booked',
            new_name='setup',
        ),
    ]
